# Generated by Django 6.0.4 on 2026-04-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(default='SP', max_length=2, verbose_name='Estado (UF)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_kwh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo (kWh/mês)')),
                ('conta_valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da conta (R$)')),
                ('tarifa_kwh', models.DecimalField(decimal_places=4, default=0.85, max_digits=6, verbose_name='Tarifa (R$/kWh)')),
                ('irradiacao', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Irradiação (hsp/dia)')),
                ('percentual_geracao', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='% de geração desejada')),
                ('reajuste_anual', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='Reajuste anual (%)')),
                ('potencia_kwp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Potência necessária (kWp)')),
                ('custo_estimado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo estimado (R$)')),
                ('economia_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Economia mensal (R$)')),
                ('payback_anos', models.PositiveSmallIntegerField(verbose_name='Payback (anos)')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado'), ('negociando', 'Em negociação'), ('fechado', 'Fechado'), ('perdido', 'Perdido')], default='novo', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='solar.cliente')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
