# Generated by Django 6.0.4 on 2026-05-14 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solar.cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='consumo_kwh',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Consumo (kWh)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='conta_valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Conta (R$)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='custo_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo  (R$)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='payback_anos',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Payback (anos)'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='potencia_kwp',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Potência  (kWp)'),
        ),
    ]
