# Generated by Django 5.1.4 on 2026-05-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_alter_cliente_criado_em_alter_cliente_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
